✨ (action.yml): add sbom_file_name input to customize SBOM file names ♻️ (action.yml): refactor filename generation for SBOM files for clarity

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -20,6 +20,10 @@ inputs:
     description: "Suffix for the SBOM files"
     required: false
     default: ""
+  sbom_file_name:
+    description: "Name for the SBOM files"
+    required: false
+    default: "[REPOSITORY]_[TAG]"
 runs:
   using: "composite"
   steps:
@@ -50,10 +54,10 @@ runs:
       run: |
         IFS=',' read -ra IMAGES <<< "${{ inputs.images }}"
         for image in "${IMAGES[@]}"; do
-          filename=$(echo $image | tr '/:' '_')
-          syft $image --scope all-layers -o syft-table > $GITHUB_WORKSPACE/${{ inputs.output_path }}/${{ inputs.sbom_file_prefix }}$filename${{ inputs.sbom_file_suffix }}.txt
-          syft $image --scope all-layers -o json | jq '.' > $GITHUB_WORKSPACE/${{ inputs.output_path }}/${{ inputs.sbom_file_prefix }}$filename${{ inputs.sbom_file_suffix }}.json
-          echo "Created files: $GITHUB_WORKSPACE/${{ inputs.output_path }}/${{ inputs.sbom_file_prefix }}$filename${{ inputs.sbom_file_suffix }}.txt and $GITHUB_WORKSPACE/${{ inputs.output_path }}/${{ inputs.sbom_file_prefix }}$filename${{ inputs.sbom_file_suffix }}.json"
+          filename=${{ inputs.sbom_file_prefix }}$(echo $image | tr '/:' '_')${{ inputs.sbom_file_suffix }}
+          syft $image --scope all-layers -o syft-table > $GITHUB_WORKSPACE/${{ inputs.output_path }}/$filename.txt
+          syft $image --scope all-layers -o json | jq '.' > $GITHUB_WORKSPACE/${{ inputs.output_path }}/$filename.json
+          echo "Created files: $GITHUB_WORKSPACE/${{ inputs.output_path }}/$filename.txt and $GITHUB_WORKSPACE/${{ inputs.output_path }}/$filename.json"
         done
 
     - name: List directory for debugging
@@ -70,9 +74,9 @@ runs:
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
         IFS=',' read -ra IMAGES <<< "${{ inputs.images }}"
         for image in "${IMAGES[@]}"; do
-          filename=$(echo $image | tr '/:' '_')
-          git add $GITHUB_WORKSPACE/${{ inputs.output_path }}/${{ inputs.sbom_file_prefix }}$filename${{ inputs.sbom_file_suffix }}.txt || echo "Failed to add ${{ inputs.sbom_file_prefix }}$filename${{ inputs.sbom_file_suffix }}.txt"
-          git add $GITHUB_WORKSPACE/${{ inputs.output_path }}/${{ inputs.sbom_file_prefix }}$filename${{ inputs.sbom_file_suffix }}.json || echo "Failed to add ${{ inputs.sbom_file_prefix }}$filename${{ inputs.sbom_file_suffix }}.json"
+          filename=${{ inputs.sbom_file_prefix }}$(echo $image | tr '/:' '_')${{ inputs.sbom_file_suffix }}
+          git add $GITHUB_WORKSPACE/${{ inputs.output_path }}/$filename.txt || echo "Failed to add $filename.txt"
+          git add $GITHUB_WORKSPACE/${{ inputs.output_path }}/$filename.json || echo "Failed to add $filename.json"
         done
         git status
         git commit -m "Update SBOM for images: ${{ inputs.images }}."
