♻️ (action.yml): refactor SBOM file handling and improve comments

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -57,7 +57,6 @@ runs:
           IFS=':' read -r -a IMAGE <<< "$image"
           REPOSITORY=${IMAGE[0]}
           TAG=${IMAGE[1]}
-          # Replace "X" with "Y"
           filename=$(echo ${{ inputs.sbom_file_name }} | sed "s|\\[REPOSITORY\\]|$REPOSITORY|g" | sed "s|\\[TAG\\]|$TAG|g")
           filename=${{ inputs.sbom_file_prefix }}$filename${{ inputs.sbom_file_suffix }}
 
@@ -83,7 +82,6 @@ runs:
           IFS=':' read -r -a IMAGE <<< "$image"
           REPOSITORY=${IMAGE[0]}
           TAG=${IMAGE[1]}
-          # Replace "X" with "Y"
           filename=$(echo ${{ inputs.sbom_file_name }} | sed "s|\\[REPOSITORY\\]|$REPOSITORY|g" | sed "s|\\[TAG\\]|$TAG|g")
           filename=${{ inputs.sbom_file_prefix }}$filename${{ inputs.sbom_file_suffix }}
 
@@ -94,7 +92,6 @@ runs:
         git commit -m "Update SBOM for images: ${{ inputs.images }}."
         git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
         
-        # Check if the current branch is a tag
         if [[ ${{ github.ref }} == refs/tags/* ]]; then
           echo "Current ref is a tag. Force pushing to update the tag."
           git push -f origin HEAD:${{ github.ref }}
@@ -108,15 +105,13 @@ runs:
         GITHUB_TOKEN: ${{ inputs.github_token }}
         DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
       run: |
-        # Check if the current branch is the default branch
         CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
 
         if [ "$CURRENT_BRANCH" != "$DEFAULT_BRANCH" ]; then
-          # Fetch and checkout the default branch
-          git fetch origin $DEFAULT_BRANCH
-          git checkout $DEFAULT_BRANCH
-          
-          # Copy SBOM files to the default branch workspace
+          # Create a temporary directory for copying files
+          TEMP_DIR=$(mktemp -d)
+
+          # Copy SBOM files to the temporary directory
           IFS=',' read -ra IMAGES <<< "${{ inputs.images }}"
           for image in "${IMAGES[@]}"; do
             IFS=':' read -r -a IMAGE <<< "$image"
@@ -125,14 +120,21 @@ runs:
             filename=$(echo ${{ inputs.sbom_file_name }} | sed "s|\\[REPOSITORY\\]|$REPOSITORY|g" | sed "s|\\[TAG\\]|$TAG|g")
             filename=${{ inputs.sbom_file_prefix }}$filename${{ inputs.sbom_file_suffix }}
 
-            # Use absolute paths for copying files
-            cp $GITHUB_WORKSPACE/${{ inputs.output_path }}/$filename.txt $GITHUB_WORKSPACE/${{ inputs.output_path }}/main_$filename.txt || echo "Failed to copy $filename.txt"
-            cp $GITHUB_WORKSPACE/${{ inputs.output_path }}/$filename.json $GITHUB_WORKSPACE/${{ inputs.output_path }}/main_$filename.json || echo "Failed to copy $filename.json"
+            cp $GITHUB_WORKSPACE/${{ inputs.output_path }}/$filename.txt $TEMP_DIR/$filename.txt || echo "Failed to copy $filename.txt"
+            cp $GITHUB_WORKSPACE/${{ inputs.output_path }}/$filename.json $TEMP_DIR/$filename.json || echo "Failed to copy $filename.json"
           done
 
-          # Add, commit and push the changes to the default branch
-          git add $GITHUB_WORKSPACE/${{ inputs.output_path }}/main_*.txt || echo "Failed to add txt files"
-          git add $GITHUB_WORKSPACE/${{ inputs.output_path }}/main_*.json || echo "Failed to add json files"
+          # Fetch and checkout the default branch
+          git fetch origin $DEFAULT_BRANCH
+          git checkout $DEFAULT_BRANCH
+
+          # Copy SBOM files from the temporary directory to the workspace
+          cp $TEMP_DIR/*.txt $GITHUB_WORKSPACE/${{ inputs.output_path }}/ || echo "Failed to copy txt files"
+          cp $TEMP_DIR/*.json $GITHUB_WORKSPACE/${{ inputs.output_path }}/ || echo "Failed to copy json files"
+
+          # Add, commit, and push the changes to the default branch
+          git add $GITHUB_WORKSPACE/${{ inputs.output_path }}/*.txt || echo "Failed to add txt files"
+          git add $GITHUB_WORKSPACE/${{ inputs.output_path }}/*.json || echo "Failed to add json files"
           git status
           git commit -m "Update SBOM files for images: ${{ inputs.images }}."
           git push origin $DEFAULT_BRANCH
